### ISSUE TITLE
Normalize models

### ISSUE THREAD

**Issue by danyfedorov** [OutOfGods/FuelCalculator#1]

**Comment by bugdie4k** [comment]
Кароче, в их лабе может случится такая, например, вполне валидная таблица.

| Date       | Trip length (km) | Fuel consumption (fuel/100km) | Fuel used |
|------------|------------------|-------------------------------|-----------|
| 05-06-2017 | 100              | 100                           | 100       |
| 05-06-2017 | 100              | 100                           | 100       |

Получается, что в этой таблице может быть две одинаковых строки ничем не отличающихся. То есть ни один набор атрибутов не может быть ключом. 3НФ можно достичь если добавить атрибут Trip ID.

Будет так.

| Trip ID | Date       | Trip length (km) | Fuel consumption (fuel/100km) | Fuel used |
|---------|------------|------------------|-------------------------------|-----------|
| 0       | 05-06-2017 | 100              | 100                           | 100       |
| 1       | 05-06-2017 | 100              | 100                           | 100       |

Вот и все.
