### ISSUE TITLE
Re-factor code

### ISSUE THREAD

**Issue by danyfedorov** [OutOfGods/FuelCalculator#3]

**Comment by danyfedorov** [comment]
Ну, я пытался. Вышло так себе, закрывать не буду.

**Comment by Caparow** [comment]
Не знаю что там с рефактором, я не стал лезть в то что пытался сделать данил
но это надо убрать
роли сильной оно не играет с тем мейном что я написал, но мне было впадлу удалять это, все
вдруг пригодилось бы

**Comment by Caparow** [comment]
Кстати, забыл сказать что удалил все док тесты
потому что эта хорошая вещь делает код нечитабельным
